apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-post-app
  namespace: blog-app-prod
  labels:
    app: blog-post-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-post-app
  template:
    metadata:
      labels:
        app: blog-post-app
    spec:
      containers:
      - name: blog-post-app
        image: blog-post-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
