apiVersion: v1
kind: Service
metadata:
  name: blog-post-app-service
  namespace: blog-app-prod
  labels:
    app: blog-post-app
spec:
  type: NodePort
  selector:
    app: blog-post-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30080
  sessionAffinity: None
